#!/bin/bash
#last update Jan. 15, 2019
DEBUG=YES
#################################################

# Define functions
#################################################
function pause(){
   read -p "$*"
}

function help(){
  echo
  echo "Usage"
  echo
  echo "    md-clean [-h|--help] \\"
  echo "               (-d <directory>|--dir <directory>) \\"
  echo "               [OPTION]..."
  echo
  echo "Options"
  echo
  echo "    -h, --help"
  echo "        Show this information"
  echo "    -d, --dir"
  echo "        optional. \\"
  echo "        define the path of the directory to list. This defaults to the current working directory. \\"
  echo "        (ie. -d=/home/user/directory)"
  echo
}
print_associative_array() {
    # declare a local **reference variable** (hence `-n`) named `array_reference`
    # which is a reference to the value stored in the first parameter
    # passed in
    echo "printing associative array: $1"
    local -n map_ref="$1"

    # print the array by iterating through all of the keys now
    for key in "${!map_ref[@]}"; do
        value="${map_ref["$key"]}"
        echo "  $key: $value"
    done
}
merge_associative_array() {
    # declare a local **reference variable** (hence `-n`) named `array_reference`
    # which is a reference to the value stored in the first parameter
    # passed in
    # echo "merging associative arrays: $1 <--- $2"
    local -n map_ref="$1"
    local -n map_ref2="$2"

    # setting the value of keys in the second array, to the value of the same key in the first array
    for key in "${!map_ref2[@]}"; do
        value="${map_ref2["$key"]}"
        echo "  $key: $value"
        map_ref["$key"]="$value"
    done
    echo "${map_ref[0]}"
    # print_associative_array "$1"
}
#################################################

# Parsing arguments passed to the script
# any arguments not defined below will be passed as arguments/options
#################################################
PASSARGS=()
for i in "$@"
do
case $i in
    -h|--help)
    help
    exit 0
    ;;
    -d=*|--dir=*)
    DIRPASSED=YES
    DIR="${i#*=}"
    shift # past argument=value
    ;;
    *)
    PASSARGS+=(${i}) # unknown option
    ;;
esac
done
#################################################
now=$(date '+%Y_%m_%d_%H_%M_%S')

if [ ! $DIRPASSED ]
then
  echo "working in directory ${PWD}"
  dir="${PWD}"
else
  if [ -d "${DIR}" ]
  then
    echo "working in directory ${DIR}"
    dir="${DIR}"
  else
    echo "supplied directory: ${DIR}, does not exist"
    exit 1
  fi
fi
# first we replace all tab characters with spaces
# find "${dir}" -type f -name "*.md" -exec sed -i 's/\t/    /g' {} \;

for f in "$dir/"*".md"
do
  if [ $DEBUG ]; then echo "filepath: $f"; fi
  FILE="${f##*/}"
  FILENAME="${FILE%.*}"
  EXT="${f##*.}"
  if [ $DEBUG ]; then echo "file: $FILE"; fi
  if [ $DEBUG ]; then echo "filename: $FILENAME"; fi
  if [ $DEBUG ]; then echo "extension: $EXT"; fi
  FRONTMATTER=$(sed -n '/^---/p;q' "$f")
  declare -A FM_ARRAY
  if [ $FRONTMATTER ]; then
    if [ $DEBUG ]; then echo "file: $FILENAME already contains frontmatter"; fi
    FRONTMATTER_END=$(($(awk '/---/ && ++n==2 {print NR;exit}' "$f")))
    if [ $DEBUG ]; then echo "the frontmatter ends on line: $FRONTMATTER_END"; fi
    cnt=0
    while read LINE
    do
    if [ "$cnt" -lt $FRONTMATTER_END ];
    then
      if [[ "$LINE" =~ .*":".* ]];  then
        LENGTH=$(($(echo $LINE | grep -o ":" | wc -l) +1))
        KEY=$(cut -d ':' -f 1 <<< "$LINE")
        VALUE=$(cut -d ':' -f 2-$LENGTH <<< "$LINE")
        if [ "$KEY" == "title" ]; then KEEPTITLE="YES"; fi
        FM_ARRAY["$KEY"]="$VALUE"
      fi
    fi
    cnt=$((cnt+1))
    done < "$f"
    # awk "NR>"$FRONTMATTER_END" && /---/ {gsub(\"-\", \"*\")} 1" "$f"
    if [ ! $KEEPTITLE ]
    then
      TITLE=$(awk "/./ { if (NR>"$FRONTMATTER_END") {print;exit}}" "$f")
      if [ $DEBUG ]; then echo "the title is: $TITLE"; fi
      SAFETITLE=$(./safetitle $TITLE)
      if [ $DEBUG ]; then echo "the safetitle is: $SAFETITLE"; fi
    fi
  else
    if [ $DEBUG ]; then echo "file: $FILENAME does not contain frontmatter"; fi
    TITLE=$(awk '/./ {print;exit}' "$f")
    if [ $DEBUG ]; then echo "the title is: $TITLE"; fi
    SAFETITLE=$(./safetitle $TITLE)
    if [ $DEBUG ]; then echo "the safetitle is: $SAFETITLE"; fi
  fi
  FM_ARRAY["title"]="$SAFETITLE"
  for key in "${!FM_ARRAY[@]}"; do echo "$key => ${FM_ARRAY[$key]}"; done
  METADATA=$(($(awk '/METADATA =========================================================================================/ {print NR;exit}' "$f") - 2))
  if [ $DEBUG ]; then echo "metadata startline is: $METADATA"; fi
  if [ "$METADATA" -gt 0 ]; then 
    if [ $DEBUG ]; then echo "file: $FILENAME contains metadata"; fi
    cnt=0
    declare -A META_ARRAY
    while read MLINE
    do
    if [ "$cnt" -gt $METADATA ];
    then
      if [[ "$MLINE" =~ .*":".* ]];  then
        LENGTH=$(($(echo $MLINE | grep -o ":" | wc -l) +1))
        MKEY=$(cut -d ':' -f 1 <<< "$MLINE")
        MVALUE=$(cut -d ':' -f 2-$LENGTH <<< "$MLINE")
        if [ "$MKEY" == "creation date" ]; then MKEY="date"; fi
        META_ARRAY["$MKEY"]="$MVALUE"
      fi
    fi
    cnt=$((cnt+1))
    done < "$f"
    # for key in "${!META_ARRAY[@]}"; do echo "$key => ${META_ARRAY[$key]}"; done
    declare -A MERGED_ARRAY
    MERGED_ARRAY=$(merge_associative_array "FM_ARRAY" "META_ARRAY")
    echo "merged array:"
    for key in "${!MERGED_ARRAY[@]}"; do echo "$key => ${MERGED_ARRAY[$key]}"; done
  else
    if [ $DEBUG ]; then echo "file: $FILENAME does not contain metadata"; fi
  fi
  echo "======================================================================"
done
